### ISSUE TITLE
Integration von Subserion

### ISSUE THREAD

**Issue by Blindie92** [bertholdm/calibre-metadata-plugin-perrypedia#3]
Moin, Calibre unterstützt ja das Sortieren mit Unterserien. Ich habe gesehen das die Momentan in der Beschreibung gespeichert werden, wenn die mit einem . verknüpft an die Serie angehängt werden, kann Calibre das Parsen und zeigt dies als Unterserie.

**Comment by bertholdm** [comment]
Hallo Blindie92,
wenn ich die Dokumentation (https://manual.calibre-ebook.com/de/sub_groups.html) richtig verstanden habe, funktioniert das nur bei benutzerdefinierten Feldern. Ein metadatenquellen-Plugin kann aber leider keine benutzerdefinierten Felder schreiben. Bitte mich zu korrigieren, wenn ich falsch liege.
Was aber wohl machbar wäre, das werde ich demnächst mal ausprobieren, ist das Kopieren von Feldinhalten in andere mit der Calibre-Vorlagensprache (https://manual.calibre-ebook.com/de/template_lang.html). Also Informationen, die jetzt im Kommentarfeld landen, in ein anderes, auch benutzerdefiniertes Feld, zu kopieren.

**Comment by Blindie92** [comment]
Sorry Für die späte Antwort, Ich habe das ohne benutzerdefinierter Felder Hinbekommen, Ich habe das Testweise mit den Atlan Miniserien gemacht, ich habe z.B. bei Serie Atlan-Miniserien.Centauri eingefügt und dann in Calibre In den Einstellungen -> Benutzeroberfläche -> Erscheinungsbild -> Schlagwortbrowser -> Kategorie mit Hierarchischen Elementen series eingefügt und dann hat es funktioniert, das funktioniert also auch mit Vordefinierten Feldern wenn man den Namen entsprechend dort einträgt.

**Comment by bertholdm** [comment]
Dann werde ich das für die nächste Version vorsehen, (mit Wahlmöglichkeit in Konfigurationseinstellungen).
Danke für die Rückmeldung.
