### ISSUE TITLE
Doppelbelegung von Namen führt zu empty results

### ISSUE THREAD

**Issue by MaxRink** [bertholdm/calibre-metadata-plugin-perrypedia#4]
Ein paar der Romane der Heftserie haben Namenskollisionen im Wiki, die dazu führen dass die Metadaten nicht gefunden werden können.

https://www.perrypedia.de/wiki/Atom-Alarm_(Roman) z.b. (Da ist die Seite des Titels ein anderes Resultat https://www.perrypedia.de/wiki/Atom-Alarm )

Das betrifft auch weite Ausgaben wie https://www.perrypedia.de/wiki/Hyperk%C3%A4lte bzw. https://www.perrypedia.de/wiki/Hyperk%C3%A4lte_(Roman)

**Comment by bertholdm** [comment]
Version 1.8.5 behebt den Fehler. Danke für's Testen!
